[package]
name = "http-router"
version = "0.1.0"
authors = ["Domenico Shura <shura1991@gmail.com>"]
edition = "2018"

[dependencies]
objc = "0.2.6"
core-foundation = "0.6.4"
objc-foundation = "0.1.1"
libc = "0.2.58"
